name: Deploy
on:
  push:
    branches:
     - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  report:
    name: Report
    runs-on: ubuntu-latest
    steps:
    - name: ref
      run: echo ${{ github.ref }}
    - name: event_name
      run: echo ${{ github.event_name }}
  deploy:
    name: Deploy Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          ${{env.IMAGE_NAME}}:${{github.sha}}
          ${{env.IMAGE_NAME}}:master
